# Generated by Django 6.0.1 on 2026-02-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_project_worker_attachment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
