# Generated by Django 6.0.1 on 2026-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_alter_task_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
